### PR TITLE
Use randomExt.pick for candleSize in sample config

### PR DESCRIPTION
**Pull request by azizmb**
Minor cleanup, since `randomExt` already exists, might as well use it to get the `candleSize`.

### CODE REVIEW

**Comment by generalectric** [comment]
Very nice! I apologize for the late response.. If you don't mind fixing the conflict I'll get it merged in

**Comment by azizmb** [comment]
@generalectric Resolved, but was too lazy to do it on my machine. Will cleanup the history and push tomorrow.

**Comment by generalectric** [comment]
Ha! OK sounds great and do you mind rebasing to develop branch?

**Comment by generalectric** [comment]
tried it out doesnt work in my case as i have more than 1 candlesize setting and end up with the same number for all my candlesizes... BUT, it does work for normal use with only 1 candlesize. 

*edit*
which really confused me because it SHOULD work and led to me trying again and works fine..... yeah its bedtime!

**Pull request merged**
